import time
import datetime
print (time.time())
print (datetime.datetime.now())
print (datetime.datetime.now().strftime("%y-%m-%d-%H-%M"))
print (datetime.date.today().strftime("%Y"))
print (datetime.date.today().strftime("%B"))
print (datetime.date.today().strftime("%W"))
print (datetime.date.today().strftime("%w"))
print (datetime.date.today().strftime("%j"))
print (datetime.date.today().strftime("%d"))
print (datetime.date.today().strftime("%A"))
